### ISSUE TITLE
NPK Deploy - Admin Group Bug

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#123]
I get error message below when running initial deployment of NPK. However, I don't get this error message when I run terraform apply right after this. 

Error: Error applying plan:

1 error occurred:
	* null_resource.cognito-add-to-admin-group: Error running command 'aws --region us-west-2 --profile <PROFILENAME> cognito-idp admin-add-user-to-group --user-pool-id us-west-2_<POOL ID> --username USER@DOMAIN.com --group npk-admins': exit status 255. Output: 
An error occurred (ResourceNotFoundException) when calling the AdminAddUserToGroup operation: Group not found.

**Comment by c6fc** [comment]
Sorry for the late reply on this - I actually discovered this on my own where there was a missing explicit dependency and fixed it around the same rime you made this post. When deployed from scratch, the add-to-admin-group command didn't appropriately wait for the group to be present first.

It should be fixed as of [this change](https://github.com/Coalfire-Research/npk/commit/17a92c1041ca6ba2bbacad7f39399d92b7d12442#diff-921a0cdfe140e08507693b24865427f1df03f7a39ad78db72c951d675fab8804L25)

Let me know if you get a chance to test it. I'll test a fresh deploy myself and close if the problem is indeed fixed.

**Comment by ArchitektApx** [comment]
Tried a fresh deployment and I too still have the same issue even after https://github.com/Coalfire-Research/npk/commit/17a92c1041ca6ba2bbacad7f39399d92b7d12442. 

Running terraform apply again or `aws --region us-west-2 --profile cognito-idp admin-add-user-to-group --user-pool-id us-west-2_ --username USER@DOMAIN.com --group npk-admins` straight after works properly tho.

**Comment by c6fc** [comment]
PR merged. I'll verify before closing.

**Comment by c6fc** [comment]
fresh deploy shows that this is resolved.
